version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - requirements: requirements.txt

sphinx:
  configuration: docs/source/conf.py


html_theme = "sphinx_rtd_theme"
html_theme_options = {
    "style_nav_header_background": "#007bff",  # Blu
}
