name: Build and Publish Python Package

on:
  push:
    branches:
      - main  # Esegui il workflow quando c'è un push sul ramo "main"
  pull_request:
    branches:
      - main  # Esegui il workflow anche quando c'è una pull request sul ramo "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specifica la versione di Python da usare

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build the package
        run: |
          python3 -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.0
        with:
          user: ${{ secrets.PYPI_USERNAME }}
          password: ${{ secrets.PYPI_PASSWORD }}
